version: '3'

networks:
  internal:
    external: false
  web:
    external: true

services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - RP_DB_HOST=database
      - RP_DB_NAME=${DB_NAME}
      - RP_DB_USER=${DB_USER}
      - RP_DB_PASSWORD=${DB_PASSWORD}
      - RP_DB_PORT=${DB_PORT}
      - RP_PORT=${RP_PORT}
      - RP_VERSION=${RP_VERSION}
    env_file:
      - ./config/.env
    volumes:
      - ./config:/src/config
    ports:
      - ${RP_PORT}:${RP_PORT}
    networks:
      - internal
      - web
    depends_on:
      - database

  database:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: postgres:14.3-alpine3.16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSRGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - internal