version: '3'

networks: 
  internal:
    external: false
  web:
    external: true

services: 
  app:
    container_name: ${APP_CONTAINER_NAME}
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: batijo/random-person:${RP_VERSION}
    restart: unless-stopped
    environment: 
      - RP_DB_HOST=database
      - RP_DB_NAME=${DB_NAME}
      - RP_DB_USER=${DB_USER}
      - RP_DB_PASSWORD=${DB_PASSWORD}
      - RP_DB_PORT=${DB_PORT}
      - RP_PORT=${RP_PORT}
      - RP_VERSION=${RP_VERSION}
    env_file:
      - ./config/.env
    volumes:
      - ./config/names.json:/src/config/names.json
      - ./config/surnames.json:/src/config/surnames.json
    ports:
      - ${RP_PORT}:${RP_PORT}
    networks: 
      - internal
      - web
    depends_on: 
      - database

  database:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSRGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - internal
  
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30